# Control Flow, Jahreem Jeffers, v0.0
# DECLARATIONS

favcolor= "red"
luckyNumber= 8
myGpa = 3.24
myAge= 16
pinappleonpizza= false

# if  Statements- Check for a condition to be True/False, do something if true.
if favcolor == "red":
print("your drip is nice.")

if myAge== 16
print("YOUR YOUNG AF!?!?")

# if-else Statement -- Check for a condition, do something for True 
if myGpa >= 3.0:
print("Congratulations on making the honor roll!")
else:
print("better luck next year. Try to study more!")

if favcolor= "red"
print("red means blood. crazy man")

else:
print("dont bother lying dude")
# if -elif- else statements -- Checks for multiple conditions
if mt=yAge > 65:
print("Congratulations on retiring!")
if myAge > 50
print("Congratulations, you have earned a bonus of 1000$")
else: 
print("You are not old enough for a bonus.")
# 1 if, 1 else, any number of elif allowed. 

# Nested if - elif- else Statements 
if myAge > 15:
print("you are eligible for a license!")
if my Gpa >= 3.5:
print(you can qualify for a new car!")
elif myGpa > 2.0:
print("you can qualify for $500 off a car!")
else:
print("you get nothing")
else:
print("are not old enough for a license")

# When doing if- elif- else statements, check for the highest value first!!!!
if myGpa > 1.5:
print("you are in danger of failing this year.")
elif myGPA > 2.0
print("you are on track to gradute")
elif myGPA > 3.0:
print("you qualify for some scholarship money!")
elif myGpa > 3.99:
print("You qualify for Bright Futures 100 percent scholarship!")
else:
print("GPA was not calculated. Please try again.")

# while Loop -- Think "MUSICAL CHAIRS" -- Used when you do NOT know how many iterations you need.
# iteration = one complete trip through a loop
x = 0
while x < 100: 
    print(f"X is currently equal to {x}")
    x += 20

while x >= 0:
    print(f"X is currently equal to {x}")
    x -= 1
    
# for Loop -- Think 'Go Fish', used when you know number of iterations needed.
print("FOR LOOP STARTS HERE")
for i in range(10) # i = iterable variable
    print(i) 
    
    print("EVEN OR ODD LOOP!") 
    for i in range(101):
    print(i)
    if i % 2 == 0: 
        print("That number is even!")
    else:
        print("That number is odd!")

# () Parentheses
# [] Square Brackets
# <> Angle Brackets 
# {} Braces 

